services:
  - type: web
    name: resume-parser-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    services:
  - type: web
    name: resume-parser-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:5000
    envVars:
      - key: PORT
        value: 5000

    envVars:
      - key: PORT
        value: 5000
