SUCCESS = "Success"
GENERAL_ERROR = "General error occurred"
ERR_PASSWORD_NOT_MATCH = "Password does not match"
UPLOAD_FAILED = "Resume upload failed"
CANDIDATE_LIST_FAILED = "Failed to list candidates"
CANDIDATE_DELETE_FAILED = "Failed to delete candidate"
REQUIREMENTS_ERROR = "Failed to process requirements"
LOGIN_FAILED = "Login failed"